# * 建立服務的範本，測試時需要調整參數使用docker-compose.override去覆寫.
version: "3.7"
# networks:
#   vnet:
volumes:
  app-data:
services:
  # TODO 預計改成直接引用Github的Dockerfile
  alpine:
    image: wayne168/alpine
    build:
      # ! 使用本地Dockerfiel
      context: ./
      # ! 使用預設分支為build context
      # context: https://github.com/panda0001/alpine.git 
      # ! 使用dev分支為build context
      # context: https://github.com/panda0001/alpine.git#dev
      # context: waynehuang@vs-ssh.visualstudio.com:v3/waynehuang/prog/alpine./
      # dockerfile: Dockerfile-alternate      
      args:
        buildno: 123
    # hostname: alpine
    volumes: 
      # - type: volume
      #   source: app-data
      #   target: /app
      - type: bind
        source: ./
        target: /app   
    # networks:
    #   vnet:
    # aliases:
    #  - test-alpine
    # depends_on:
    #   - postgres
